[package]
name = "zarchive"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0.69"
smallvec = "1.8.1"
thiserror = "1.0.31"
zstd-sys = "2.0.1"

[dev-dependencies]
rayon = "1.5.3"

[build-dependencies]
cxx-build = "1.0.69"
