name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: default
    - name: Install zstd
      run: sudo apt install libzstd-dev
    - name: Run tests
      run: cargo test
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: default
    - name: Get zstd header
      run: Invoke-WebRequest -Uri https://raw.githubusercontent.com/facebook/zstd/dev/lib/zstd.h -OutFile include\zstd.h
    - name: Run tests
      run: cargo test
