name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Install libzstd
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install libzstd-dev
    - name: Get zstd Header
      if: matrix.os == 'windows-latest'
      run: Invoke-WebRequest -Uri https://raw.githubusercontent.com/facebook/zstd/dev/lib/zstd.h -OutFile include\zstd.h
    - name: Run tests
      run: cargo test
